import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/app/ui/Header/Header";
import Footer from "@/app/ui/Footer/footer";
import Dashboard from "@/app/ui/Dashboard/dashboard";
import './style.css';
import { NextUIProvider } from "@nextui-org/system";

import { poppins } from "@/app/ui/fonts";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
      <NextUIProvider>
          <main className="light text-foreground bg-background flex flex-col items-center">
              <Header/>
              <Dashboard/>
              <Footer/>
          </main>
      </NextUIProvider>
      </body>
    </html>
);
}
